MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "mobilenet_v2-ecbe2b5.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "MNV2-FPN-RETINANET"
    FREEZE_CONV_BODY_AT: 0
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  USE_SYNCBN: False
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
#  TRAIN: ("coco_2017_train",)
#  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000,80000,120000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
  WARMUP_METHOD: "constant"
