MODEL:
  META_ARCHITECTURE: "GeneralizedFaceNet_Head"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  RETINANET_ON: True
  USE_SYNCBN: False
  BACKBONE:
    CONV_BODY: "FACE-NET-IR-50"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 512
  RPN:
    RPN_HEAD: "ArcFace"
    CLASS_NUMS: 93962  #93962


DATASETS:
  TRAIN: ("celebrity_face",)
  TEST: ("coco_2014_minival",) #
#
#  dataset size:  3923138 / 86875  86,876 ids/3,923,399
#  dataset size:  2829773 / 93962  93,979 ids/2,830,146
INPUT:
  MIN_SIZE_TRAIN: (128,128)
  MAX_SIZE_TRAIN: 112
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 0
SOLVER:
  # Assume 4 gpus
  BASE_LR: 0.1
  CHECKPOINT_PERIOD: 4448
  WEIGHT_DECAY: 0.0001
  STEPS: (35584,71168,88960)
  MAX_ITER: 110000
  IMS_PER_BATCH: 720
  DIVS_NUMS_PER_BATCH: 2
#  WARMUP_METHOD: "constant"
